apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-native-app
  namespace: default
  labels:
    app: cloud-native
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cloud-native
  template:
    metadata:
      labels:
        app: cloud-native
    spec:
      containers:
        - name: monitoring-app
          image: 084298470880.dkr.ecr.us-west-1.amazonaws.com/cloud-native-monitoring-repo:latest
          ports:
            - containerPort: 5000
